### ISSUE TITLE
300x250 | default,QA_functional_test | All browser(W,M) | Frame animation time mismatch with ref 

### ISSUE THREAD

**Issue by Shahnul-sebpo** [sebpo1/USCS_1568#1]
https://user-images.githubusercontent.com/95062434/159606363-b5d3bbd8-18ad-416f-9433-fbce7e5d05aa.mp4

![1](https://user-images.githubusercontent.com/95062434/159606378-d80001a3-5db6-4f4f-8f87-9c85c5e24a6f.jpg)

**Comment by mukimut-sebpo** [comment]
First second is spent on ad loading and appearing which is not shown in story board, Please close.

**Comment by bikash-sebpo** [comment]
ok
