### ISSUE TITLE
300x250 | default | All browser(W, M) | Wrong clicktag

### ISSUE THREAD

**Issue by arnab-sebpo** [sebpo1/USCS_1568#14]
**Wrong clicktag shows on CTA portions.**

https://user-images.githubusercontent.com/95363813/159805430-0663930a-bfe4-4374-bbaa-4a2ae0caa188.mp4

![image](https://user-images.githubusercontent.com/95363813/159805792-cecfa510-8515-4a4b-ac05-745d9f751f40.png)

**Comment by jahid-sebpo** [comment]
solved

**Comment by arnab-sebpo** [comment]
fixed
