### ISSUE TITLE
300x250 | default | All browser(W, M) | Clicktag is not working

### ISSUE THREAD

**Issue by arnab-sebpo** [sebpo1/USCS_1568#15]
**Clicktag is not working on the marked areas.**

![image](https://user-images.githubusercontent.com/95363813/159806061-5eb8e1c0-4db8-4652-b2a8-009b505b184e.png)

**Comment by jahid-sebpo** [comment]
Solved

**Comment by jahid-sebpo** [comment]
For blue part, clicktag will work on text.

**Comment by arnab-sebpo** [comment]
ok
