### ISSUE TITLE
300x250 | default | All browser(W, M) | Wrong clicktag

### ISSUE THREAD

**Issue by arnab-sebpo** [sebpo1/USCS_1568#16]
**Wrong clicktag shows on bottom portions.
And clicktag is not working on bottom left and bottom right.**

https://user-images.githubusercontent.com/95363813/159807613-6690b7d6-cc9b-40ff-bbb9-9241c76f4bc0.mp4

**Comment by jahid-sebpo** [comment]
solved

**Comment by arnab-sebpo** [comment]
fixed
