### ISSUE TITLE
300x250 | default,QA_functional_test | All browser(W,M) | Frame1 text position mismatch with ref

### ISSUE THREAD

**Issue by Shahnul-sebpo** [sebpo1/USCS_1568#2]
![2](https://user-images.githubusercontent.com/95062434/159609871-2cb7bfae-0771-4920-b20b-a8b8c714ba58.jpg)

![2 1](https://user-images.githubusercontent.com/95062434/159611131-b1688c88-ba71-4945-8c5e-1eabff7e5ffe.jpg)

**Comment by mukimut-sebpo** [comment]
fixed
