### ISSUE TITLE
300x250 | default,QA_functional_test | All browser(W,M) | Frame3 font style, font size, text position mismatch with ref

### ISSUE THREAD

**Issue by Shahnul-sebpo** [sebpo1/USCS_1568#4]
![4 1](https://user-images.githubusercontent.com/95062434/159614148-2ebfbdae-1734-4118-8daa-8c71d8fd50be.jpg)

![4](https://user-images.githubusercontent.com/95062434/159614160-4d54f319-f405-4db0-b538-7880c29e46ea.jpg)

**Comment by mukimut-sebpo** [comment]
fixed
