### ISSUE TITLE
300x250 | default,QA_functional_test | All browser(W,M) | Frame4 font style, font size, text position mismatch with ref

### ISSUE THREAD

**Issue by Shahnul-sebpo** [sebpo1/USCS_1568#5]
![5 1](https://user-images.githubusercontent.com/95062434/159615498-4910c30d-c8e8-4aa3-bc2e-910d2c69f72a.jpg)

![5](https://user-images.githubusercontent.com/95062434/159615502-186f6f0c-1cd8-4cff-9427-6f86ab0bfafa.jpg)

**Comment by mukimut-sebpo** [comment]
fixed

**Comment by bikash-sebpo** [comment]
OK
